sudo: required
language: node_js
node_js:
  - 6.11.4
env:
  global:
  - CXX=g++-4.8
  - COVERALLS_SERVICE_NAME=travis-ci
    # COVERALLS_REPO_TOKEN (encrypted)
  - secure: HwELk4+NjL4768aMjHlmymn94qDuoxfMwOdPuhUhvdbTMYmQZknCokmbGqWYgmk1gY6js6+4HmAEB23U3VOCLTD68HswPzSNejDtYfAJrGEElqD9HBvj9IJQuwtcoX4V+AtBxBl3d3gfuVpokFHl0Y5Ob+tFGFRyp9mV04bXrE3EwEkxhHlKLjMiZk9BBpMVeMFycID+d1qEpiA8CF1ehwbU+GGVfHHe5q+OOCSjL7YC6URNVR2R9i544hI+PnlF2UhCF3fFSizGDDsugMMmt6boHI62tPnfhNDD83DTtS8RIN+I8YF0kcJU2ArQ8K3FR2BoRmb7beqejf7Sz6Er9ZkjRYO4wBFwRTeYKEBfg5MtsaABw4hQxlYk1KKkETO/KXhTqXMWDZUV6RVzt7nZzP6NILqOeRtjdFJW9fyGq1ekjRFCjNUprxDE641JdZFOYXojzhLLXqb2vPEKowxbq4aFI6FFKWMoUTs8tANh7Z1CfshR9/RmzxrmdskLfy1ENL6X8hUreMUvCJvXY8dBDy8kiLS6N1DXHEIc5S+wt68feiVmVErMjLypOcC0Cx++Iiri4C08u1UhTMgvQth+O+gQz+jKgnilxe3A9ccG7vBTSIfCQ57s2Mb4cnyFDTsuuAJZHsJJOhDlXaQL674rDLw7LrbQqz+t7/Jn0JuiPd4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
install:
- sudo unlink /usr/bin/g++
- sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
- npm install -g npm
- npm install
- npm install -g grunt-cli
- grunt test
- grunt lint
after_success:
- grunt coverage-report; grunt coveralls
