sudo: required
language: node_js
node_js:
- 6.11.4
env:
  global:
  - CXX=g++-4.8
  - COVERALLS_SERVICE_NAME=travis-ci
  - secure: HwELk4+NjL4768aMjHlmymn94qDuoxfMwOdPuhUhvdbTMYmQZknCokmbGqWYgmk1gY6js6+4HmAEB23U3VOCLTD68HswPzSNejDtYfAJrGEElqD9HBvj9IJQuwtcoX4V+AtBxBl3d3gfuVpokFHl0Y5Ob+tFGFRyp9mV04bXrE3EwEkxhHlKLjMiZk9BBpMVeMFycID+d1qEpiA8CF1ehwbU+GGVfHHe5q+OOCSjL7YC6URNVR2R9i544hI+PnlF2UhCF3fFSizGDDsugMMmt6boHI62tPnfhNDD83DTtS8RIN+I8YF0kcJU2ArQ8K3FR2BoRmb7beqejf7Sz6Er9ZkjRYO4wBFwRTeYKEBfg5MtsaABw4hQxlYk1KKkETO/KXhTqXMWDZUV6RVzt7nZzP6NILqOeRtjdFJW9fyGq1ekjRFCjNUprxDE641JdZFOYXojzhLLXqb2vPEKowxbq4aFI6FFKWMoUTs8tANh7Z1CfshR9/RmzxrmdskLfy1ENL6X8hUreMUvCJvXY8dBDy8kiLS6N1DXHEIc5S+wt68feiVmVErMjLypOcC0Cx++Iiri4C08u1UhTMgvQth+O+gQz+jKgnilxe3A9ccG7vBTSIfCQ57s2Mb4cnyFDTsuuAJZHsJJOhDlXaQL674rDLw7LrbQqz+t7/Jn0JuiPd4=
  matrix:
    secure: MhiNAUv3GyNloghg+07kVArVc1TWR6/g0xKWU8y8t/3A9rMn087GKFJdtJkUPSfjWh7jkLmN203LuRHrHc5lx0Rvpt1J6IhQzwlT18SpXn5Kzm3VOn1OZCqNs+Ns5bLozqETHpcFt/moqX2xDdUXWF7pYWkDIyVQtFgWXqPBejHecu6UCnoUgg3moMHjsXfyoHaOY45ttvr/NpIoGG349g4LKxTmN0w0UhDQwnhpSb7E2PnIRAxGf/zBnQS9liRf696d5xL5mr5WQYu3hW37WZyi9FICqqxbziMnlFJ6HDeO4hHzYRxQrNQKCqSmwLRCJZOXpdlyhUFhb+ZFAsLflX6ZOsEDVDKb+cWtJHL+j3kKxlEcrCZd3L1NUTVCrnbkdKTjlow4lHQ8IlBjCkZhzpycqWhM4bwsgvsLUqeP4x//KCBoypCebmtqJc03Aj7CR+XUVmZbxb5OoWYycqDDSioZr2V9e8Xk6N1jiz05kbgD07hOFf+zci88hRM2hYSemsJ6ZZb55VzeaLd6Y+ra2P8ZMeITJa3rEtvYhmjLRI3fp6uefohVdd+7sw+qHOGc6s0GlMOlz5wc92IsZPPoq+P1wcMgf9U10MWerweY2D++TgDEFaXjYdV0dSm5hUpCDqWGT7gRRNOqUUaKPkbBYQpq73LPh97Nswh+z+2gz0Y=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
install:
- sudo unlink /usr/bin/g++
- sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
- npm install -g npm
- npm install
- npm install -g grunt-cli
- grunt test
- grunt lint
after_success:
- grunt coverage-report; grunt coveralls
