sudo: required
language: node_js
node_js:
  - "4.5.0"
env:
  - CXX=g++-4.8
  - COVERALLS_SERVICE_NAME=travis-ci
  # COVERALLS_REPO_TOKEN (encrypted)
  - secure: "RrzGnJHZ2E2kvtOhzFBmbmESFfZZa+U79EOtBOtj1uTmfxqglPQr1lfi52E3HlIqDznjE4u+JMh1aZ4b9ma/geonB05XF7eInOSAP966jgiLzpSofjAxbPlMV8fMPtU8wZQvMHW3JeA20jjVGfBtiYyAbTpyx4BKS/LwZKT0NcQ5KkNxlHnHlUlXxqvgqHVx5cHHjW4bPNH6tyEYf348ztFu6Lro9EEEq6UVUJAN0nhIv2CRG1vFnSKSEjjWfRUcyU7bjEthnsk1kzp25s5hRN6M12Mt+Bi8dMjgyqsHwgrVs0/SVoWLINOGuOy6I8IP8e6ZtDs5eE5D/iPXU/JoAZaImBlJzwYqNHeAOpF+x8MYPikhxlJVWGSkn6cU92sbGxtyeVatJjn/tkyWtCmicU+tjwqSK5l3MmQnRqZlruYRid99hpsf9usWs4whfStZleR1DWhWWt47cHLXQnrDMHWUGhldxcJ/eYbWcKuF/88wbJemoggHEHW0LXd5wJ+UF07obyDSP9+dnF+z1IHRz8XG6qI5CNKz+rI4JJ8nFSnEZcqUwuMSKIjFOcE5dTIjGt4rg9wUb39DiVKHqOEWDXijFAF7YoXZWkDdhbkazCtgCiQdCH6GTOqxzorUgyMq+SfVEr6TO6XshTsd8rhF7kSbeNvHkZwLNZrxVz1yp/8="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - sudo unlink /usr/bin/g++
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - npm install
  - npm install -g grunt-cli
  - npm install coveralls --save
  - grunt test
  - grunt lint

after_success:
  - grunt coverage-report && cat report/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
