fiwareaikos:
  image: fiware-aiakos
  ports:
   - 3000:3000
  environment: 
   - ADM_PASSWORD
   - ADM_USERNAME
   - ADM_TENANT_NAME
   - ADM_TENANT_ID
   - KEYSTONE_IP
   - OS_USER_DOMAIN_NAME
   - OS_PROJECT_DOMAIN_NAME
fiware-aiakos-aceptance:
  image: fiware-aiakos-acceptance
  links:
  -  fiwareaikos
  environment:
   - ADM_PASSWORD
   - ADM_USERNAME
   - ADM_TENANT_NAME
   - ADM_TENANT_ID
   - OS_USER_DOMAIN_NAME
   - OS_PROJECT_DOMAIN_NAME
   - KEYSTONE_IP
   - Region1
