#----------------------------------------------------------------------------
# Aiakos application section (mandatory)
#----------------------------------------------------------------------------
app:
  port: 3000		# App listen port

#-----------------------------------------------------------------------------
#  openstack admin (mandatory)
#-----------------------------------------------------------------------------
openstack:
  host: 'cloud.lab.fiware.org'
  port: '4731'
  username: ''		# admin openstack user
  password: ''		# admin openstack password

